mongoid:
  host: localhost
  port: 27017
  db: hatetw
mongoid_test:
  host: localhost
  port: 27017
  db: hatetw_test

mention_gobis:
  - ...反応無いと寂しいんだが
  - というものがあってだな...
  - はもう読んだよな？
  - は当然もう読んだよな？
  - がまだ片付いてない件
  - が手つかずの件
  - のことも思い出してあげて下さい
  - とは何だったのか
  - 、いつやるの？今でしょ！
  - 、ちゃんとやる気あるの？
  - くらい、忙しいけど見とけよ
  - の件はどうなった？
  - があるんで読んどけよ
  - ってのがあったの覚えてる？
  - 読んどけよ
  - やっとけよ
read_replies:
  - 処理しといた
  - 完了にしました
  - ほいほい
  - closeね
  - closed = trueだん
  - 乙
  - おつい
  - やるじゃん
udon_replies:
  - うどんと聞いて
  - ずぞぞぞ
  - うどんばっか食いやがって...
  - ねぎは野菜に入りません
  - 違う！貴様の食べているうどんは真のうどんではない！
  - うどんに反応する程度の能力
